/**
 * Git-surface text hygiene (product-readiness Phase 4, shared by T-PRD14 /
 * T-PRD15).
 *
 * The agent drafts commit messages and PR descriptions; the house rules forbid
 * two things on those surfaces regardless of what the model emits:
 *  - AI self-attribution footers ("Generated with X", "Co-authored-by: <AI>",
 *    "Pull Request opened by …", bare AI-vendor links);
 *  - decorative emoji (titles must be fully emoji-free; bodies keep only the
 *    functional status markers ❌ ✅ ⚠️).
 *
 * AI council (codex-cli 0.134.0 + gemini 0.41.2, 2026-05-31, UNANIMOUS on
 * fork C): STRIP, do not reject. A deterministic sanitiser gives an always-on
 * Core a hard compliance guarantee that beats probabilistic prompt-following;
 * the removals are surfaced as `warnings` so the caller can show what changed.
 * These low-level helpers are the strip primitives; the PR-body / PR-title
 * sanitisers that compose them live in `pr-description.ts`.
 */

/** Status markers that survive a body strip — functional, not decorative. */
const STATUS_WHITELIST = new Set(['❌', '✅', '⚠']); // ❌ ✅ ⚠

/**
 * One emoji grapheme: a pictographic base plus any trailing variation selector,
 * ZWJ-joined pictographs, or skin-tone modifiers. Built fresh per call so the
 * shared `g` flag's `lastIndex` never leaks across invocations.
 */
function emojiRegex(): RegExp {
  return /(?:\p{Extended_Pictographic}|\p{Emoji_Presentation})(?:️|‍\p{Extended_Pictographic}|\p{Emoji_Modifier})*/gu;
}

/** Strip the variation selector / ZWJ glue so a match can be checked vs the whitelist. */
function emojiBase(match: string): string {
  return match.replace(/[️‍]/g, '');
}

/**
 * Remove decorative emoji. With `keepStatus` (default), the functional markers
 * ❌ ✅ ⚠️ survive; everything else — including the universal blacklist
 * (🤖 🚀 🎉 ✨ 🔥 💡 👍 ❤️) and any ZWJ / skin-tone sequence — is dropped.
 * Titles pass `keepStatus: false` to forbid every emoji.
 */
export function stripDecorativeEmoji(text: string, opts: { keepStatus?: boolean } = {}): string {
  const keepStatus = opts.keepStatus ?? true;
  return text.replace(emojiRegex(), (match) => {
    if (keepStatus && STATUS_WHITELIST.has(emojiBase(match))) return match;
    return '';
  });
}

/** Whether `text` carries any emoji (the whitelisted status markers don't count). */
export function hasEmoji(text: string, opts: { ignoreStatus?: boolean } = {}): boolean {
  const ignoreStatus = opts.ignoreStatus ?? true;
  const re = emojiRegex();
  let match: RegExpExecArray | null;
  while ((match = re.exec(text)) !== null) {
    if (match[0].length === 0) {
      re.lastIndex += 1; // guard against a zero-width match stalling the loop
      continue;
    }
    if (ignoreStatus && STATUS_WHITELIST.has(emojiBase(match[0]))) continue;
    return true;
  }
  return false;
}

/**
 * Lines that are AI self-attribution and must never reach a git surface. Kept
 * focused so a human's legitimate `Co-authored-by:` trailer or an unrelated
 * "generated by the build" line is not collateral.
 */
const ATTRIBUTION_PATTERNS: RegExp[] = [
  /co-?authored-by:.*\b(claude|augment|gpt|chatgpt|copilot|gemini|anthropic|openai)\b/i,
  /\bgenerated\s+(with|by)\b.*\b(claude(\s+code)?|augment(\s+code)?|copilot|gemini|chatgpt|anthropic|openai)\b/i,
  /\bpull request opened by\b/i,
  /\bissue opened by\b/i,
  /\b(augmentcode|anthropic|openai|claude)\.(com|ai)\b/i,
];

/**
 * Drop every line that matches an attribution pattern. Returns the cleaned text
 * plus how many lines were removed (0 → nothing was an attribution footer).
 */
export function stripAttributionLines(text: string): { text: string; removed: number } {
  const lines = text.split('\n');
  const kept: string[] = [];
  let removed = 0;
  for (const line of lines) {
    if (ATTRIBUTION_PATTERNS.some((re) => re.test(line))) {
      removed += 1;
      continue;
    }
    kept.push(line);
  }
  return { text: kept.join('\n'), removed };
}

/** Collapse 3+ consecutive newlines to a single blank line. */
export function collapseBlankLines(text: string): string {
  return text.replace(/\n{3,}/g, '\n\n');
}
