/**
 * Kotlin DTO codegen from the protocol package.
 *
 * Start simple (per road-to-mvp T-102): one explicit spec → one Kotlin file
 * with kotlinx.serialization data classes. The spec below is the single
 * source of truth shared with `packages/protocol/src/schema.ts`; a future
 * iteration can derive it from the Zod schemas via reflection.
 *
 * Run: `pnpm exec tsx scripts/codegen.ts` (or `task codegen`).
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(__dirname, '..');

type Field = { name: string; kotlinType: string };
type DataClass = { name: string; fields: Field[]; doc?: string };

const KOTLIN_PACKAGE = 'de.event4u.agent.protocol';

const classes: DataClass[] = [
  {
    name: 'Envelope',
    doc: 'One NDJSON line on the Core <-> client channel.',
    fields: [
      { name: 'messageId', kotlinType: 'String' },
      { name: 'messageType', kotlinType: 'String' },
      { name: 'data', kotlinType: 'JsonElement' },
      { name: 'done', kotlinType: 'Boolean' },
    ],
  },
  { name: 'PingResponse', fields: [{ name: 'result', kotlinType: 'String' }] },
  { name: 'EchoRequest', fields: [{ name: 'text', kotlinType: 'String' }] },
  { name: 'EchoResponse', fields: [{ name: 'text', kotlinType: 'String' }] },
];

function emitClass(dc: DataClass): string {
  const doc = dc.doc ? `/** ${dc.doc} */\n` : '';
  const fields = dc.fields.map((f) => `    val ${f.name}: ${f.kotlinType},`).join('\n');
  return `${doc}@Serializable\ndata class ${dc.name}(\n${fields}\n)`;
}

const header = `// GENERATED by scripts/codegen.ts — DO NOT EDIT BY HAND.
// Source of truth: packages/protocol/src/schema.ts
package ${KOTLIN_PACKAGE}

import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement
`;

const body = classes.map(emitClass).join('\n\n');
const out = `${header}\n${body}\n`;

const target = join(
  repoRoot,
  'clients/jetbrains/src/main/kotlin',
  ...KOTLIN_PACKAGE.split('.'),
  'Protocol.kt',
);
mkdirSync(dirname(target), { recursive: true });
writeFileSync(target, out, 'utf8');

process.stdout.write(`codegen: wrote ${classes.length} DTOs -> ${target}\n`);
