/**
 * Kotlin DTO codegen from the protocol package.
 *
 * Start simple (per road-to-mvp T-102): one explicit spec → one Kotlin file
 * with kotlinx.serialization data classes. The spec below is the single
 * source of truth shared with `packages/protocol/src/schema.ts`; a future
 * iteration can derive it from the Zod schemas via reflection.
 *
 * Run: `pnpm exec tsx scripts/codegen.ts` (or `task codegen`).
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(__dirname, '..');

// A field maps a Zod property to a Kotlin `data class` property. `kotlinType`
// is emitted verbatim, so `List<T>` and nullable `T?` are expressed directly.
// `default` (e.g. `null`, `emptyList()`) makes the property optional on the
// wire — kotlinx.serialization fills it when the JSON omits the key.
type Field = { name: string; kotlinType: string; default?: string };
type DataClass = { name: string; fields: Field[]; doc?: string };

const KOTLIN_PACKAGE = 'de.event4u.agent.protocol';

const classes: DataClass[] = [
  {
    name: 'Envelope',
    doc: 'One NDJSON line on the Core <-> client channel.',
    fields: [
      { name: 'messageId', kotlinType: 'String' },
      { name: 'messageType', kotlinType: 'String' },
      { name: 'data', kotlinType: 'JsonElement' },
      { name: 'done', kotlinType: 'Boolean' },
    ],
  },
  { name: 'PingResponse', fields: [{ name: 'result', kotlinType: 'String' }] },
  { name: 'EchoRequest', fields: [{ name: 'text', kotlinType: 'String' }] },
  { name: 'EchoResponse', fields: [{ name: 'text', kotlinType: 'String' }] },

  // --- multi-project: workspace folders (road-to-multi-project Phase B) ---
  {
    name: 'WorkspaceFolder',
    doc: 'A project root the IDE window currently has open.',
    fields: [
      { name: 'uri', kotlinType: 'String' },
      { name: 'stableId', kotlinType: 'String' },
      { name: 'displayName', kotlinType: 'String' },
      { name: 'kind', kotlinType: 'String' },
    ],
  },
  {
    name: 'RootIndexStatus',
    doc: 'Per-root index status. `state` is one of indexing | ready | error.',
    fields: [
      { name: 'stableId', kotlinType: 'String' },
      { name: 'state', kotlinType: 'String' },
      { name: 'fileCount', kotlinType: 'Int' },
      { name: 'totalFiles', kotlinType: 'Int?', default: 'null' },
      { name: 'message', kotlinType: 'String?', default: 'null' },
    ],
  },
  {
    name: 'ConnectRequest',
    doc: 'Connection handshake; reports every open root.',
    fields: [
      { name: 'workspaceFolders', kotlinType: 'List<WorkspaceFolder>', default: 'emptyList()' },
    ],
  },
  {
    name: 'ConnectResponse',
    fields: [
      { name: 'ack', kotlinType: 'Boolean' },
      { name: 'roots', kotlinType: 'List<WorkspaceFolder>' },
      { name: 'status', kotlinType: 'List<RootIndexStatus>' },
    ],
  },
  {
    name: 'WorkspaceFoldersChangedRequest',
    doc: 'Delta of opened / closed roots.',
    fields: [
      { name: 'added', kotlinType: 'List<WorkspaceFolder>', default: 'emptyList()' },
      { name: 'removed', kotlinType: 'List<String>', default: 'emptyList()' },
    ],
  },
  {
    name: 'WorkspaceFoldersChangedResponse',
    fields: [
      { name: 'ack', kotlinType: 'Boolean' },
      { name: 'status', kotlinType: 'List<RootIndexStatus>' },
    ],
  },
  {
    name: 'RootStatusResponse',
    fields: [{ name: 'status', kotlinType: 'List<RootIndexStatus>' }],
  },
];

function emitClass(dc: DataClass): string {
  const doc = dc.doc ? `/** ${dc.doc} */\n` : '';
  const fields = dc.fields
    .map((f) => `    val ${f.name}: ${f.kotlinType}${f.default ? ` = ${f.default}` : ''},`)
    .join('\n');
  return `${doc}@Serializable\ndata class ${dc.name}(\n${fields}\n)`;
}

const header = `// GENERATED by scripts/codegen.ts — DO NOT EDIT BY HAND.
// Source of truth: packages/protocol/src/schema.ts
package ${KOTLIN_PACKAGE}

import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement
`;

const body = classes.map(emitClass).join('\n\n');
const out = `${header}\n${body}\n`;

const target = join(
  repoRoot,
  'clients/jetbrains/src/main/kotlin',
  ...KOTLIN_PACKAGE.split('.'),
  'Protocol.kt',
);
mkdirSync(dirname(target), { recursive: true });
writeFileSync(target, out, 'utf8');

process.stdout.write(`codegen: wrote ${classes.length} DTOs -> ${target}\n`);
