// GENERATED by scripts/codegen.ts — DO NOT EDIT BY HAND.
// Source of truth: packages/protocol/src/schema.ts
package de.event4u.agent.protocol

import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement

/** One NDJSON line on the Core <-> client channel. */
@Serializable
data class Envelope(
    val messageId: String,
    val messageType: String,
    val data: JsonElement,
    val done: Boolean,
)

@Serializable
data class PingResponse(
    val result: String,
)

@Serializable
data class EchoRequest(
    val text: String,
)

@Serializable
data class EchoResponse(
    val text: String,
)

/** A project root the IDE window currently has open. */
@Serializable
data class WorkspaceFolder(
    val uri: String,
    val stableId: String,
    val displayName: String,
    val kind: String,
)

/** Per-root index status. `state` is one of indexing | ready | error. */
@Serializable
data class RootIndexStatus(
    val stableId: String,
    val state: String,
    val fileCount: Int,
    val totalFiles: Int? = null,
    val message: String? = null,
)

/** Connection handshake; reports every open root. */
@Serializable
data class ConnectRequest(
    val workspaceFolders: List<WorkspaceFolder> = emptyList(),
)

@Serializable
data class ConnectResponse(
    val ack: Boolean,
    val roots: List<WorkspaceFolder>,
    val status: List<RootIndexStatus>,
)

/** Delta of opened / closed roots. */
@Serializable
data class WorkspaceFoldersChangedRequest(
    val added: List<WorkspaceFolder> = emptyList(),
    val removed: List<String> = emptyList(),
)

@Serializable
data class WorkspaceFoldersChangedResponse(
    val ack: Boolean,
    val status: List<RootIndexStatus>,
)

@Serializable
data class RootStatusResponse(
    val status: List<RootIndexStatus>,
)

/** One chunk of raw PTY output; seq is monotonic per session. */
@Serializable
data class OutputChunk(
    val seq: Int,
    val data: String,
    val at: String,
)

/** A discrete input request the session is blocked on. */
@Serializable
data class PendingInput(
    val inputRequestId: String,
    val prompt: String,
    val at: String,
)

/** Replay window returned on subscribe / reconnect. */
@Serializable
data class ReplaySlice(
    val chunks: List<OutputChunk>,
    val droppedChunks: Int,
    val droppedBytes: Int,
    val firstSeqAvailable: Int,
    val nextSeq: Int,
    val restartRequired: Boolean,
)

/** Subscribe to a session; the Core streams terminal events on this id. */
@Serializable
data class TerminalSubscribeRequest(
    val commandId: String,
    val surfaceId: String,
    val replayFromSeq: Int = 0,
)

/** First envelope of the subscribe stream — replay + current state. */
@Serializable
data class TerminalSubscribeResponse(
    val subscriptionId: String,
    val status: String,
    val pendingInput: PendingInput? = null,
    val replay: ReplaySlice,
)

/** Write to stdin — raw, or answer a pending request (first-write-wins). */
@Serializable
data class TerminalInputRequest(
    val commandId: String,
    val surfaceId: String,
    val data: String,
    val inputRequestId: String? = null,
)

@Serializable
data class TerminalInputResponse(
    val accepted: Boolean,
    val reason: String? = null,
    val winningSurfaceId: String? = null,
)

@Serializable
data class TerminalResizeRequest(
    val commandId: String,
    val cols: Int,
    val rows: Int,
)

@Serializable
data class TerminalResizeResponse(
    val ack: Boolean,
)
