// GENERATED by scripts/codegen.ts — DO NOT EDIT BY HAND.
// Source of truth: packages/protocol/src/schema.ts
package de.event4u.agent.protocol

import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement

/** One NDJSON line on the Core <-> client channel. */
@Serializable
data class Envelope(
    val messageId: String,
    val messageType: String,
    val data: JsonElement,
    val done: Boolean,
)

@Serializable
data class PingResponse(
    val result: String,
)

@Serializable
data class EchoRequest(
    val text: String,
)

@Serializable
data class EchoResponse(
    val text: String,
)
