package de.event4u.agent

import de.event4u.agent.protocol.Envelope
import java.io.BufferedReader
import java.io.BufferedWriter
import java.io.InputStreamReader
import java.io.OutputStreamWriter
import java.util.UUID
import java.util.concurrent.ConcurrentHashMap
import java.util.concurrent.SynchronousQueue
import java.util.concurrent.TimeUnit
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.buildJsonObject

/**
 * Spawns the Node Agent Core sidecar and exposes request/response calls over
 * its NDJSON stdio channel, correlated by `messageId`.
 *
 * Modelled on Spike 0.3b's RpcConsumer (validated 5000 token-events <3s) and
 * the [Envelope] DTO generated by `scripts/codegen.ts`. The transport is the
 * NDJSON envelope chosen in ADR-003 and reconfirmed by the AI Council
 * (gemini + codex/gpt-5, 2026-05-29).
 */
class SidecarClient(
    private val serverPath: String,
    private val nodePath: String = "node",
) {
    private val json = Json { ignoreUnknownKeys = true }
    private val pending = ConcurrentHashMap<String, SynchronousQueue<Envelope>>()

    private var process: Process? = null
    private var writer: BufferedWriter? = null
    private var readerThread: Thread? = null

    fun start() {
        if (process != null) return
        val proc = ProcessBuilder(nodePath, serverPath)
            .redirectErrorStream(false)
            .start()
        process = proc
        writer = BufferedWriter(OutputStreamWriter(proc.outputStream, Charsets.UTF_8))

        readerThread = Thread {
            val reader = BufferedReader(InputStreamReader(proc.inputStream, Charsets.UTF_8))
            reader.useLines { lines ->
                lines.forEach { line ->
                    if (line.isBlank()) return@forEach
                    runCatching { json.decodeFromString(Envelope.serializer(), line) }
                        .getOrNull()
                        ?.let { env -> pending.remove(env.messageId)?.put(env) }
                }
            }
        }.apply {
            isDaemon = true
            start()
        }
    }

    /** Send a request and block up to [timeoutMs] for the correlated reply. */
    fun request(messageType: String, data: JsonObject, timeoutMs: Long = 5000): Envelope? {
        val w = writer ?: error("sidecar not started")
        val messageId = UUID.randomUUID().toString()
        val queue = SynchronousQueue<Envelope>()
        pending[messageId] = queue

        val envelope = buildJsonObject {
            put("messageId", JsonPrimitive(messageId))
            put("messageType", JsonPrimitive(messageType))
            put("data", data)
            put("done", JsonPrimitive(true))
        }
        synchronized(w) {
            w.write(json.encodeToString(JsonObject.serializer(), envelope))
            w.write("\n")
            w.flush()
        }
        return queue.poll(timeoutMs, TimeUnit.MILLISECONDS).also { pending.remove(messageId) }
    }

    /** Ping the sidecar; true on a `pong` reply. */
    fun healthy(): Boolean {
        val res = request("ping", buildJsonObject {}) ?: return false
        val result = (res.data as? JsonObject)?.get("result") as? JsonPrimitive
        return res.messageType == "ping" && result?.content == "pong"
    }

    fun dispose() {
        process?.destroy()
        process = null
        writer = null
        pending.clear()
    }
}
