package de.event4u.agent

import de.event4u.agent.protocol.Envelope
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.buildJsonObject
import java.io.BufferedReader
import java.io.BufferedWriter
import java.io.File
import java.io.InputStreamReader
import java.io.OutputStreamWriter
import java.util.UUID
import java.util.concurrent.ArrayBlockingQueue
import java.util.concurrent.ConcurrentHashMap
import java.util.concurrent.SynchronousQueue
import java.util.concurrent.TimeUnit

/**
 * Spawns the Node Agent Core sidecar and exposes request/response calls over
 * its NDJSON stdio channel, correlated by `messageId`.
 *
 * Modelled on Spike 0.3b's RpcConsumer (validated 5000 token-events <3s) and
 * the [Envelope] DTO generated by `scripts/codegen.ts`. The transport is the
 * NDJSON envelope chosen in ADR-003 and reconfirmed by the AI Council
 * (gemini + codex/gpt-5, 2026-05-29).
 */
class SidecarClient(
    private val serverPath: String,
    private val nodePath: String = "node",
    private val workingDir: String? = null,
) {
    private val json = Json { ignoreUnknownKeys = true }
    private val pending = ConcurrentHashMap<String, SynchronousQueue<Envelope>>()

    /**
     * Streaming correlations — invoked for EVERY envelope of a `messageId` and
     * self-removing on the terminal `done:true`. Checked before [pending] so a
     * streamed `done:false` token never consumes the one-shot path.
     */
    private val streaming = ConcurrentHashMap<String, (Envelope) -> Unit>()

    private var process: Process? = null
    private var writer: BufferedWriter? = null
    private var readerThread: Thread? = null

    fun start() {
        if (process != null) return
        val proc =
            ProcessBuilder(nodePath, serverPath)
                .redirectErrorStream(false)
                .apply {
                    // Spawn the sidecar with the open project as its working
                    // directory. The Core defaults its `workspaceRoot` (the root
                    // every read/search/write tool resolves against) to
                    // `process.cwd()`; without this the sidecar inherits the
                    // IDE's launch directory and analyses the wrong tree.
                    workingDir?.let { File(it) }?.takeIf(File::isDirectory)?.let { directory(it) }
                }
                .start()
        process = proc
        writer = BufferedWriter(OutputStreamWriter(proc.outputStream, Charsets.UTF_8))

        readerThread =
            Thread {
                val reader = BufferedReader(InputStreamReader(proc.inputStream, Charsets.UTF_8))
                reader.useLines { lines ->
                    lines.forEach { line ->
                        if (line.isBlank()) return@forEach
                        runCatching { json.decodeFromString(Envelope.serializer(), line) }
                            .getOrNull()
                            ?.let { env ->
                                val stream = streaming[env.messageId]
                                if (stream != null) {
                                    stream(env)
                                } else {
                                    pending.remove(env.messageId)?.put(env)
                                }
                            }
                    }
                }
            }.apply {
                isDaemon = true
                start()
            }
    }

    /** Send a request and block up to [timeoutMs] for the correlated reply. */
    fun request(
        messageType: String,
        data: JsonObject,
        timeoutMs: Long = DEFAULT_TIMEOUT_MS,
    ): Envelope? {
        val w = writer ?: error("sidecar not started")
        val messageId = UUID.randomUUID().toString()
        val queue = SynchronousQueue<Envelope>()
        pending[messageId] = queue

        val envelope =
            buildJsonObject {
                put("messageId", JsonPrimitive(messageId))
                put("messageType", JsonPrimitive(messageType))
                put("data", data)
                put("done", JsonPrimitive(true))
            }
        synchronized(w) {
            w.write(json.encodeToString(JsonObject.serializer(), envelope))
            w.write("\n")
            w.flush()
        }
        return queue.poll(timeoutMs, TimeUnit.MILLISECONDS).also { pending.remove(messageId) }
    }

    /**
     * Send a streaming request. [onToken] fires for each intermediate
     * `done:false` envelope; the call blocks up to [timeoutMs] and returns the
     * terminal `done:true` envelope. Used by `chatSend`, whose tokens arrive as
     * `done:false` frames. Run this off the EDT — it blocks on the stream.
     */
    fun requestStream(
        messageType: String,
        data: JsonObject,
        timeoutMs: Long = STREAM_TIMEOUT_MS,
        onToken: (Envelope) -> Unit,
    ): Envelope? {
        val w = writer ?: error("sidecar not started")
        val messageId = UUID.randomUUID().toString()
        val terminal = ArrayBlockingQueue<Envelope>(1)
        streaming[messageId] = { env ->
            if (env.done) {
                streaming.remove(messageId)
                terminal.offer(env)
            } else {
                onToken(env)
            }
        }

        val envelope =
            buildJsonObject {
                put("messageId", JsonPrimitive(messageId))
                put("messageType", JsonPrimitive(messageType))
                put("data", data)
                put("done", JsonPrimitive(true))
            }
        synchronized(w) {
            w.write(json.encodeToString(JsonObject.serializer(), envelope))
            w.write("\n")
            w.flush()
        }
        return terminal.poll(timeoutMs, TimeUnit.MILLISECONDS).also { streaming.remove(messageId) }
    }

    /** Ping the sidecar; true on a `pong` reply. */
    fun healthy(): Boolean {
        val res = request("ping", buildJsonObject {}) ?: return false
        val result = (res.data as? JsonObject)?.get("result") as? JsonPrimitive
        return res.messageType == "ping" && result?.content == "pong"
    }

    fun dispose() {
        process?.destroy()
        process = null
        writer = null
        pending.clear()
        streaming.clear()
    }

    private companion object {
        const val DEFAULT_TIMEOUT_MS = 5000L
        const val STREAM_TIMEOUT_MS = 120_000L
    }
}
